config/routes.rb
# == Route Map
#
#              Prefix Verb   URI Pattern                                     Controller#Action
#                 app GET    /app(.:format)                                  app#index
#                root GET    /                                               session#new
#              planes GET    /planes(.:format)                               planes#index
#                     POST   /planes(.:format)                               planes#create
#           new_plane GET    /planes/new(.:format)                           planes#new
#          edit_plane GET    /planes/:id/edit(.:format)                      planes#edit
#               plane GET    /planes/:id(.:format)                           planes#show
#                     PATCH  /planes/:id(.:format)                           planes#update
#                     PUT    /planes/:id(.:format)                           planes#update
#                     DELETE /planes/:id(.:format)                           planes#destroy
#     flight_bookings GET    /flights/:flight_id/bookings(.:format)          bookings#index
#                     POST   /flights/:flight_id/bookings(.:format)          bookings#create
#  new_flight_booking GET    /flights/:flight_id/bookings/new(.:format)      bookings#new
# edit_flight_booking GET    /flights/:flight_id/bookings/:id/edit(.:format) bookings#edit
#      flight_booking GET    /flights/:flight_id/bookings/:id(.:format)      bookings#show
#                     PATCH  /flights/:flight_id/bookings/:id(.:format)      bookings#update
#                     PUT    /flights/:flight_id/bookings/:id(.:format)      bookings#update
#                     DELETE /flights/:flight_id/bookings/:id(.:format)      bookings#destroy
#             flights GET    /flights(.:format)                              flights#index
#                     POST   /flights(.:format)                              flights#create
#          new_flight GET    /flights/new(.:format)                          flights#new
#         edit_flight GET    /flights/:id/edit(.:format)                     flights#edit
#              flight GET    /flights/:id(.:format)                          flights#show
#                     PATCH  /flights/:id(.:format)                          flights#update
#                     PUT    /flights/:id(.:format)                          flights#update
#                     DELETE /flights/:id(.:format)                          flights#destroy
#          edit_users GET    /users/edit(.:format)                           users#edit
#               users GET    /users(.:format)                                users#index
#                     POST   /users(.:format)                                users#create
#            new_user GET    /users/new(.:format)                            users#new
#                user GET    /users/:id(.:format)                            users#show
#                     PATCH  /users/:id(.:format)                            users#update
#                     PUT    /users/:id(.:format)                            users#update
#                     DELETE /users/:id(.:format)                            users#destroy
#              signup GET    /signup(.:format)                               users#new
#               login GET    /login(.:format)                                session#new
#                     POST   /login(.:format)                                session#create
#              logout DELETE /logout(.:format)                               session#destroy
#

Rails.application.routes.draw do

  get '/app' => 'app#index'

    root :to => 'app#index'
   #root :to => 'session#new'

  resources :planes
  resources :flights do
    resources :bookings
  end

  resources :users , :except => [:edit] do 
      collection do 
        get '/edit' => 'users#edit'
      end
    end 

  get '/signup' => 'users#new'
  get '/login' => 'session#new'  #page for a new session (login)
  post '/login' => 'session#create' #create a new session (login)
  get '/logout' => 'session#destroy' #delete a session (log out) 
              
  
end

app/models/plane.rb
# == Schema Information
#
# Table name: planes
#
#  id         :integer          not null, primary key
#  name       :string
#  aisle      :integer
#  seat       :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Plane < ActiveRecord::Base

  belongs_to :flight
  validates :seat, :numericality => { :greater_than => 0}
  validates :seat, :numericality => { :less_than_or_equal_to => 6}
  validates :aisle, :numericality => {:greater_than => 0}
  validates :aisle, :numericality => { :less_than_or_equal_to => 20}
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  before_action :set_plane, only: [:show, :edit, :update, :destroy]

  # GET /planes
  # GET /planes.json
  def index
    @planes = Plane.all
  end

  # GET /planes/1
  # GET /planes/1.json
  def show
  end

  # GET /planes/new
  def new
    @plane = Plane.new
  end

  # GET /planes/1/edit
  def edit
  end

  # POST /planes
  # POST /planes.json
  def create
    @plane = Plane.new(plane_params)

    respond_to do |format|
      if @plane.save
        format.html { redirect_to @plane, notice: 'Plane was successfully created.' }
        format.json { render :show, status: :created, location: @plane }
      else
        format.html { render :new }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planes/1
  # PATCH/PUT /planes/1.json
  def update
    respond_to do |format|
      if @plane.update(plane_params)
        format.html { redirect_to @plane, notice: 'Plane was successfully updated.' }
        format.json { render :show, status: :ok, location: @plane }
      else
        format.html { render :edit }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planes/1
  # DELETE /planes/1.json
  def destroy
    @plane.destroy
    respond_to do |format|
      format.html { redirect_to planes_url, notice: 'Plane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plane
      @plane = Plane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plane_params
      params.require(:plane).permit(:name, :aisle, :seat)
    end
end

app/helpers/planes_helper.rb
module PlanesHelper
end

app/views/planes/_form.html.erb
<%= form_for(@plane) do |f| %>
  <% if @plane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plane.errors.count, "error") %> prohibited this plane from being saved:</h2>

      <ul>
      <% @plane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :aisle %><br>
    <%= f.number_field :aisle %>
  </div>
  <div class="field">
    <%= f.label :seat %><br>
    <%= f.number_field :seat %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/planes/edit.html.erb
<h1>Editing Plane</h1>

<%= render 'form' %>

<%= link_to 'Show', @plane %> |
<%= link_to 'Back', planes_path %>

app/views/planes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Planes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Aisle</th>
      <th>Seat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planes.each do |plane| %>
      <tr>
        <td><%= plane.name %></td>
        <td><%= plane.aisle %></td>
        <td><%= plane.seat %></td>
        <td><%= link_to 'Show', plane %></td>
        <td><%= link_to 'Edit', edit_plane_path(plane) %></td>
        <td><%= link_to 'Destroy', plane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plane', new_plane_path %>

app/views/planes/new.html.erb
<h1>New Plane</h1>

<%= render 'form' %>

<%= link_to 'Back', planes_path %>

app/views/planes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plane.name %>
</p>

<p>
  <strong>Aisle:</strong>
  <%= @plane.aisle %>
</p>

<p>
  <strong>Seat:</strong>
  <%= @plane.seat %>
</p>

<%= link_to 'Edit', edit_plane_path(@plane) %> |
<%= link_to 'Back', planes_path %>